# Nombre de la aplicacion
spring.application.name=app-cloud

# Puerto del servidor
server.port=8080

# ===================================================
# Configuracion Oracle Cloud (Autonomous Database)
# ===================================================
# Reemplazar con los valores del Wallet descargado desde Oracle Cloud
spring.datasource.url=jdbc:oracle:thin:@${DB_TNS_NAME}?TNS_ADMIN=${WALLET_PATH}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Pool de conexiones
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
# update crea las tablas si no existen, en prod usar validate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===================================================
# Configuración de AWS S3 (Personalizada)
# ===================================================
APP_AWS_ACCESS_KEY_ID=${APP_AWS_ACCESS_KEY_ID:}
APP_AWS_SECRET_ACCESS_KEY=${APP_AWS_SECRET_ACCESS_KEY:}
APP_AWS_SESSION_TOKEN=${APP_AWS_SESSION_TOKEN:}

# Variable para el bucket
aws.s3.bucket=bucket-app-cloud


# ===================================================
# Configuración del Servidor de Validación (issuer)
# ===================================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://appcloudauth.b2clogin.com/8c788a54-6ef0-44a7-942c-0235a1fcfec7/v2.0
